name: academia_da_comunicacao
description: >-
  App mobile da Academia da Comunicação replicando os fluxos do QConcursos com integrações Pix.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  go_router: ^13.2.1
  dio: ^5.4.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.6
  firebase_messaging: ^14.7.9
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  package_info_plus: ^5.0.1
  flutter_markdown: ^0.6.18+1
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/planos.json
    - assets/data/dashboard_home.json
    - assets/data/operations_readiness.json
    - assets/data/questoes.json
    - assets/data/simulados.json
